# Frontend deployment configuration
name = "tsinda-pro-frontend"
compatibility_date = "2024-02-13"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "18.18.0"
